# Generated by Django 2.2.4 on 2021-04-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0004_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
