# Generated by Django 2.2.4 on 2021-04-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0006_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
