# Generated by Django 2.2.4 on 2021-04-29 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
