# Generated by Django 2.2.4 on 2021-04-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0009_remove_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='genre',
            field=models.ManyToManyField(related_name='director_genres', to='app_orm.Genre'),
        ),
    ]
