# Generated by Django 2.2.4 on 2021-05-03 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0010_director_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='genre',
        ),
    ]
