# Generated by Django 2.2.4 on 2021-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0014_auto_20210504_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='blanck', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
